---
title: "join application and publication"
author: "Chris"
date: "4/12/2021"
output: html_document
---

## 1. Set up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
library(data.table)
```

## 2. Load application and publication files
## The application file is too large to unzip in R so we recommend unzipping the files manually then running the code
```{r}
# set directory ex: setwd("/Users/username/Downloads")
setwd("")

# The application file may be too large to read into memory on some computers
# If this is the case you can split the file into smaller pieces like so:
# app <- fread("application.tsv", sep="\t", nrows = 100000, skip = 0) 
# where nrows is the number of rows to read from the file and skip is the number 
# of rows to skip from the start of the file

app <- fread("application.tsv", sep="\t")
pub <- fread("publication.tsv", sep="\t")
```
## 3. Rename columns that are the same across the two files
```{r}
colnames(app)[colnames(app) == 'id'] <- 'id_app'
colnames(app)[colnames(app) == 'date'] <- 'date_app'
colnames(app)[colnames(app) == 'country'] <- 'country_app'

colnames(pub)[colnames(pub) == 'id'] <- 'id_pub'
colnames(pub)[colnames(pub) == 'date'] <- 'date_pub'
colnames(pub)[colnames(pub) == 'country'] <- 'country_pub'
```


## 3. Merge application and publication data using the document_number column
```{r}
merged <- merge(pub, app, by = "document_number")
```
